from pathlib import Path

path = Path('src/data/npo.ts')
text = path.read_text(encoding='utf-8')
needle = '\n];\n'
if needle not in text:
    raise SystemExit('array end not found')

extra = r'''
{
  id: "npo-006",
  category: "NPO und Gemeinnützigkeit",
  topic: "Steuerliche Vorteile",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welche Bereiche einer gemeinnützigen Körperschaft sind grundsätzlich von Körperschaft- und Gewerbesteuer befreit?",
  options: [
    "Ideeller Bereich, Vermögensverwaltung und Zweckbetrieb",
    "Nur der ideelle Bereich",
    "Nur der Zweckbetrieb",
    "Auch jeder steuerpflichtige wirtschaftliche Geschäftsbetrieb",
  ],
  correctAnswer: 0,
  explanation: "Die Steuerbefreiungen erfassen grundsätzlich den ideellen Bereich, die Vermögensverwaltung und Zweckbetriebe. Ein steuerpflichtiger wirtschaftlicher Geschäftsbetrieb bleibt grundsätzlich steuerpflichtig.",
  reference: "§ 5 Abs. 1 Nr. 9 KStG; § 3 Nr. 6 GewStG",
  hint: "Nicht jede Tätigkeit einer gemeinnützigen Körperschaft ist automatisch steuerfrei.",
  tags: ["Steuerbefreiung", "KStG", "GewStG"],
},
{
  id: "npo-007",
  category: "NPO und Gemeinnützigkeit",
  topic: "Wirtschaftlicher Geschäftsbetrieb",
  type: "single-choice",
  difficulty: "mittel",
  question: "Bis zu welcher Einnahmengrenze bleiben steuerpflichtige wirtschaftliche Geschäftsbetriebe ab 2026 nach § 64 Abs. 3 AO von Körperschaft- und Gewerbesteuer verschont?",
  options: ["35.000 €", "45.000 €", "50.000 €", "100.000 €"],
  correctAnswer: 2,
  explanation: "Ab 2026 gilt nach dem in der Wissensdatenbank zugrunde gelegten Rechtsstand eine Einnahmengrenze von 50.000 € einschließlich Umsatzsteuer.",
  reference: "§ 64 Abs. 3 AO",
  tags: ["wirtschaftlicher Geschäftsbetrieb", "Freigrenze", "50.000 €"],
},
{
  id: "npo-008",
  category: "NPO und Gemeinnützigkeit",
  topic: "Umsatzsteuer",
  type: "true-false",
  difficulty: "mittel",
  question: "Gemeinnützige Körperschaften sind generell von der Umsatzsteuer befreit.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 1,
  explanation: "Eine allgemeine Umsatzsteuerbefreiung für gemeinnützige Körperschaften gibt es nicht. Je nach Leistung kommen Steuerbefreiungen, der ermäßigte Steuersatz oder der Regelsteuersatz in Betracht.",
  reference: "§ 4 UStG; § 12 Abs. 2 Nr. 8 UStG",
  tags: ["Umsatzsteuer", "Steuerbefreiung", "ermäßigter Steuersatz"],
},
{
  id: "npo-009",
  category: "NPO und Gemeinnützigkeit",
  topic: "Satzung",
  type: "single-choice",
  difficulty: "mittel",
  question: "Was muss sich nach § 59 AO aus der Satzung ergeben?",
  options: [
    "Nur der Name der Körperschaft",
    "Der steuerbegünstigte Zweck und die Art seiner Verwirklichung",
    "Nur die Höhe der Mitgliedsbeiträge",
    "Nur die Zusammensetzung des Vorstands",
  ],
  correctAnswer: 1,
  explanation: "Der steuerbegünstigte Zweck und die Art seiner Verwirklichung müssen aus der Satzung hervorgehen. Zusätzlich muss die tatsächliche Geschäftsführung diesen Vorgaben entsprechen.",
  reference: "§ 59 AO",
  tags: ["Satzung", "Zweckverwirklichung", "§59 AO"],
},
{
  id: "npo-010",
  category: "NPO und Gemeinnützigkeit",
  topic: "Grundprinzipien",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welcher Grundsatz verlangt, dass eine Körperschaft grundsätzlich nur ihre steuerbegünstigten Satzungszwecke verfolgt?",
  options: ["Selbstlosigkeit", "Ausschließlichkeit", "Unmittelbarkeit", "Vermögensbindung"],
  correctAnswer: 1,
  explanation: "Die Ausschließlichkeit nach § 56 AO verlangt, dass die Körperschaft nur ihre steuerbegünstigten Satzungszwecke verfolgt.",
  reference: "§ 56 AO",
  tags: ["Ausschließlichkeit", "§56 AO"],
},
{
  id: "npo-011",
  category: "NPO und Gemeinnützigkeit",
  topic: "Grundprinzipien",
  type: "single-choice",
  difficulty: "mittel",
  question: "Was bedeutet Unmittelbarkeit im Gemeinnützigkeitsrecht grundsätzlich?",
  options: [
    "Die Körperschaft verwirklicht ihre Zwecke grundsätzlich selbst",
    "Die Körperschaft muss jede Tätigkeit unentgeltlich ausführen",
    "Die Körperschaft darf keine Hilfspersonen einsetzen",
    "Die Körperschaft darf nur im Inland tätig sein",
  ],
  correctAnswer: 0,
  explanation: "Unmittelbarkeit bedeutet grundsätzlich, dass die Körperschaft ihre steuerbegünstigten Zwecke selbst verwirklicht. Hilfspersonen dürfen eingesetzt werden, wenn deren Tätigkeit gesteuert, überwacht und dokumentiert wird.",
  reference: "§ 57 AO",
  tags: ["Unmittelbarkeit", "Hilfsperson", "§57 AO"],
},
{
  id: "npo-012",
  category: "NPO und Gemeinnützigkeit",
  topic: "Mildtätigkeit",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welche Besonderheit gilt bei mildtätigen Zwecken nach § 53 AO?",
  options: [
    "Es muss stets die Allgemeinheit gefördert werden",
    "Es können auch individuell hilfebedürftige Personen unterstützt werden",
    "Es dürfen ausschließlich juristische Personen gefördert werden",
    "Mildtätigkeit ist nur bei Religionsgemeinschaften möglich",
  ],
  correctAnswer: 1,
  explanation: "Mildtätige Zwecke unterstützen persönlich, wirtschaftlich oder aufgrund besonderer Ereignisse hilfebedürftige Personen. Anders als bei § 52 AO muss nicht die Allgemeinheit gefördert werden.",
  reference: "§ 53 AO",
  tags: ["Mildtätigkeit", "Hilfebedürftigkeit", "§53 AO"],
},
{
  id: "npo-013",
  category: "NPO und Gemeinnützigkeit",
  topic: "Vermögensbindung",
  type: "true-false",
  difficulty: "mittel",
  question: "Das Vermögen einer gemeinnützigen Körperschaft muss bei Auflösung oder Zweckwegfall steuerbegünstigt gebunden sein.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 0,
  explanation: "Die Vermögensbindung muss eindeutig in der Satzung geregelt sein. Das Vermögen darf bei Auflösung oder Zweckwegfall nicht frei an Mitglieder verteilt werden.",
  reference: "§ 55 AO; Anlage 1 zu § 60 AO",
  tags: ["Vermögensbindung", "Auflösung", "Satzung"],
},
{
  id: "npo-014",
  category: "NPO und Gemeinnützigkeit",
  topic: "Mittelverwendung",
  type: "single-choice",
  difficulty: "mittel",
  question: "Bis wann müssen zeitnah zu verwendende Mittel grundsätzlich eingesetzt werden?",
  options: [
    "Noch im Zuflussjahr",
    "Bis zum Ende des auf den Zufluss folgenden Jahres",
    "Spätestens in den beiden auf den Zufluss folgenden Kalender- oder Wirtschaftsjahren",
    "Innerhalb von fünf Jahren",
  ],
  correctAnswer: 2,
  explanation: "Zeitnah zu verwendende Mittel sind grundsätzlich spätestens in den beiden auf den Zufluss folgenden Kalender- oder Wirtschaftsjahren für die steuerbegünstigten Zwecke einzusetzen.",
  reference: "§ 55 Abs. 1 Nr. 5 AO",
  tags: ["zeitnahe Mittelverwendung", "Zwei-Jahres-Frist", "§55 AO"],
},
{
  id: "npo-015",
  category: "NPO und Gemeinnützigkeit",
  topic: "Mittelverwendung",
  type: "single-choice",
  difficulty: "mittel",
  question: "Für welche Körperschaften entfällt nach dem Rechtsstand 2026 die Pflicht zur zeitnahen Mittelverwendung?",
  options: [
    "Für alle Körperschaften",
    "Für Körperschaften mit jährlichen Einnahmen von höchstens 100.000 €",
    "Nur für Stiftungen",
    "Nur für Körperschaften ohne Arbeitnehmer",
  ],
  correctAnswer: 1,
  explanation: "Nach dem in der Wissensdatenbank zugrunde gelegten Rechtsstand gilt die Pflicht zur zeitnahen Mittelverwendung ab 2026 nicht für Körperschaften mit jährlichen Einnahmen von höchstens 100.000 €.",
  reference: "§ 55 Abs. 1 Nr. 5 AO",
  tags: ["100.000 €", "Mittelverwendung", "2026"],
},
{
  id: "npo-016",
  category: "NPO und Gemeinnützigkeit",
  topic: "Rücklagen",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welche Rücklage ist nach § 62 AO grundsätzlich zulässig?",
  options: [
    "Eine Rücklage ohne erkennbaren Zweck und ohne Dokumentation",
    "Eine zweckgebundene Rücklage für ein konkretes Vorhaben",
    "Eine Rücklage zur späteren Ausschüttung an Mitglieder",
    "Eine Rücklage zur dauerhaften Finanzierung privater Ausgaben des Vorstands",
  ],
  correctAnswer: 1,
  explanation: "§ 62 AO erlaubt unter anderem zweckgebundene Rücklagen, Wiederbeschaffungsrücklagen und freie Rücklagen. Zweck, Betrag und geplante Verwendung müssen nachvollziehbar dokumentiert sein.",
  reference: "§ 62 AO",
  tags: ["Rücklagen", "zweckgebundene Rücklage", "§62 AO"],
},
{
  id: "npo-017",
  category: "NPO und Gemeinnützigkeit",
  topic: "Rücklagen",
  type: "true-false",
  difficulty: "mittel",
  question: "Eine freie Rücklage kann ohne betragsmäßige Begrenzung gebildet werden.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 1,
  explanation: "Die freie Rücklage ist gesetzlich begrenzt. Sie darf nur innerhalb der in § 62 AO vorgesehenen Höchstbeträge gebildet werden.",
  reference: "§ 62 Abs. 1 Nr. 3 AO",
  tags: ["freie Rücklage", "Begrenzung", "§62 AO"],
},
{
  id: "npo-018",
  category: "NPO und Gemeinnützigkeit",
  topic: "Tätigkeitsbereiche",
  type: "single-choice",
  difficulty: "leicht",
  question: "Welcher Tätigkeitsbereich umfasst typischerweise Spenden, echte Mitgliedsbeiträge und Zuschüsse ohne Leistungsaustausch?",
  options: ["Ideeller Bereich", "Vermögensverwaltung", "Zweckbetrieb", "Steuerpflichtiger wirtschaftlicher Geschäftsbetrieb"],
  correctAnswer: 0,
  explanation: "Spenden, echte Mitgliedsbeiträge und Zuschüsse ohne Leistungsaustausch gehören typischerweise zum ideellen Bereich.",
  reference: "§§ 51 ff. AO",
  tags: ["ideeller Bereich", "Spenden", "Mitgliedsbeiträge"],
},
{
  id: "npo-019",
  category: "NPO und Gemeinnützigkeit",
  topic: "Tätigkeitsbereiche",
  type: "single-choice",
  difficulty: "leicht",
  question: "Welcher Bereich umfasst typischerweise die langfristige Vermietung eigenen Vermögens oder verzinsliche Kapitalanlagen?",
  options: ["Ideeller Bereich", "Vermögensverwaltung", "Zweckbetrieb", "Wirtschaftlicher Geschäftsbetrieb"],
  correctAnswer: 1,
  explanation: "Die langfristige Vermietung oder Verpachtung eigenen Vermögens und verzinsliche Kapitalanlagen gehören typischerweise zur Vermögensverwaltung.",
  reference: "§ 14 AO",
  tags: ["Vermögensverwaltung", "Vermietung", "Kapitalanlage"],
},
{
  id: "npo-020",
  category: "NPO und Gemeinnützigkeit",
  topic: "Zweckbetrieb",
  type: "single-choice",
  difficulty: "schwer",
  question: "Welche Voraussetzung gehört zu einem Zweckbetrieb nach § 65 AO?",
  options: [
    "Die Tätigkeit dient unmittelbar der Verwirklichung der Satzungszwecke",
    "Die Tätigkeit muss stets Verluste erzielen",
    "Die Tätigkeit darf keinerlei Einnahmen erzielen",
    "Die Tätigkeit muss ausschließlich Mitgliedern offenstehen",
  ],
  correctAnswer: 0,
  explanation: "Ein Zweckbetrieb muss der unmittelbaren Verwirklichung der steuerbegünstigten Satzungszwecke dienen, hierfür erforderlich sein und darf nur unvermeidbar mit nicht begünstigten Betrieben konkurrieren.",
  reference: "§ 65 AO",
  tags: ["Zweckbetrieb", "§65 AO", "Wettbewerb"],
},
{
  id: "npo-021",
  category: "NPO und Gemeinnützigkeit",
  topic: "Wirtschaftlicher Geschäftsbetrieb",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welches Beispiel gehört typischerweise zu einem steuerpflichtigen wirtschaftlichen Geschäftsbetrieb?",
  options: [
    "Eine echte Spende ohne Gegenleistung",
    "Ein Vereinsfest mit entgeltlichem Getränkeverkauf ohne unmittelbaren Zweckbezug",
    "Eine zweckgebundene öffentliche Förderung",
    "Ein echter Mitgliedsbeitrag ohne Sonderleistung",
  ],
  correctAnswer: 1,
  explanation: "Vereinsfeste, Werbung, Warenverkauf oder Gastronomie ohne unmittelbaren Zweckbezug gehören typischerweise zum steuerpflichtigen wirtschaftlichen Geschäftsbetrieb.",
  reference: "§ 14 AO; § 64 AO",
  tags: ["wirtschaftlicher Geschäftsbetrieb", "Vereinsfest", "Warenverkauf"],
},
{
  id: "npo-022",
  category: "NPO und Gemeinnützigkeit",
  topic: "Tätigkeitsbereiche",
  type: "true-false",
  difficulty: "leicht",
  question: "Eine gemeinnützige Körperschaft kann gleichzeitig Tätigkeiten in allen vier steuerlichen Bereichen ausüben.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 0,
  explanation: "Die Einordnung erfolgt tätigkeitsbezogen. Eine Körperschaft kann gleichzeitig einen ideellen Bereich, Vermögensverwaltung, Zweckbetriebe und steuerpflichtige wirtschaftliche Geschäftsbetriebe haben.",
  reference: "§§ 14, 64–68 AO",
  tags: ["vier Sphären", "Tätigkeitsbereiche", "Zuordnung"],
},
{
  id: "npo-023",
  category: "NPO und Gemeinnützigkeit",
  topic: "Satzung",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welche Aussage trifft auf den Bescheid nach § 60a AO zu?",
  options: [
    "Er bestätigt endgültig die tatsächliche Geschäftsführung",
    "Er stellt die formelle Satzungsmäßigkeit gesondert fest",
    "Er ersetzt den Freistellungsbescheid für alle Zukunft",
    "Er bestätigt automatisch die Umsatzsteuerbefreiung",
  ],
  correctAnswer: 1,
  explanation: "Der § 60a-Bescheid stellt die formelle Satzungsmäßigkeit fest. Ob die tatsächliche Geschäftsführung den Vorgaben entspricht, wird dadurch noch nicht bestätigt.",
  reference: "§ 60a AO",
  tags: ["§60a AO", "Satzungsmäßigkeit", "Feststellungsbescheid"],
},
{
  id: "npo-024",
  category: "NPO und Gemeinnützigkeit",
  topic: "Tatsächliche Geschäftsführung",
  type: "single-choice",
  difficulty: "mittel",
  question: "Womit wird die tatsächliche Geschäftsführung einer gemeinnützigen Körperschaft typischerweise nachgewiesen?",
  options: [
    "Nur mit der Satzung",
    "Mit Buchführung, Tätigkeitsberichten, Protokollen, Verträgen und Mittelverwendungsnachweisen",
    "Nur mit Kontoauszügen",
    "Nur mit einer Bestätigung des Vorstands",
  ],
  correctAnswer: 1,
  explanation: "Die tatsächliche Geschäftsführung wird anhand der praktischen Umsetzung geprüft. Dazu gehören insbesondere Buchführung, Tätigkeitsberichte, Protokolle, Verträge und Nachweise zur Mittelverwendung.",
  reference: "§ 63 AO",
  tags: ["tatsächliche Geschäftsführung", "Nachweise", "§63 AO"],
},
{
  id: "npo-025",
  category: "NPO und Gemeinnützigkeit",
  topic: "Freistellungsbescheid",
  type: "true-false",
  difficulty: "mittel",
  question: "Ein Freistellungsbescheid bestätigt für den geprüften Zeitraum grundsätzlich auch die ordnungsgemäße tatsächliche Geschäftsführung.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 0,
  explanation: "Der Freistellungsbescheid bestätigt für den geprüften Zeitraum, dass die steuerbegünstigten Voraussetzungen tatsächlich eingehalten wurden.",
  reference: "§ 63 AO",
  tags: ["Freistellungsbescheid", "tatsächliche Geschäftsführung"],
},
{
  id: "npo-026",
  category: "NPO und Gemeinnützigkeit",
  topic: "Spenden",
  type: "single-choice",
  difficulty: "leicht",
  question: "Welche Voraussetzung muss eine Spende grundsätzlich erfüllen?",
  options: [
    "Sie muss freiwillig und ohne Gegenleistung erfolgen",
    "Sie muss immer in Bargeld geleistet werden",
    "Sie darf nur von Mitgliedern stammen",
    "Sie muss an einen wirtschaftlichen Geschäftsbetrieb gezahlt werden",
  ],
  correctAnswer: 0,
  explanation: "Eine Spende muss freiwillig, unentgeltlich und zur Förderung steuerbegünstigter Zwecke geleistet werden.",
  reference: "§ 10b EStG",
  tags: ["Spende", "Unentgeltlichkeit", "§10b EStG"],
},
{
  id: "npo-027",
  category: "NPO und Gemeinnützigkeit",
  topic: "Spenden",
  type: "single-choice",
  difficulty: "mittel",
  question: "Wie ist eine Zahlung einzuordnen, wenn der Zahlende dafür eine konkrete Werbeleistung erhält?",
  options: ["Spende", "Mitgliedsbeitrag", "Sponsoring bzw. Leistungsaustausch", "Mildtätige Zuwendung"],
  correctAnswer: 2,
  explanation: "Eine konkrete Werbeleistung spricht gegen eine unentgeltliche Spende und für Sponsoring beziehungsweise einen steuerlich zu beurteilenden Leistungsaustausch.",
  reference: "§ 10b EStG; § 1 Abs. 1 Nr. 1 UStG",
  tags: ["Sponsoring", "Gegenleistung", "Spende"],
},
{
  id: "npo-028",
  category: "NPO und Gemeinnützigkeit",
  topic: "Mitgliedsbeiträge",
  type: "single-choice",
  difficulty: "mittel",
  question: "Wann kann ein Mitgliedsbeitrag steuerlich teilweise als Entgelt zu behandeln sein?",
  options: [
    "Wenn er jährlich gezahlt wird",
    "Wenn damit konkrete Sonderleistungen abgegolten werden",
    "Wenn die Mitgliederversammlung ihn beschlossen hat",
    "Wenn er per Lastschrift eingezogen wird",
  ],
  correctAnswer: 1,
  explanation: "Werden konkrete Leistungen wie Kurse, Eintritt oder besondere Nutzungsrechte abgegolten, kann der Beitrag ganz oder teilweise Entgeltcharakter haben.",
  reference: "§ 1 Abs. 1 Nr. 1 UStG",
  tags: ["Mitgliedsbeiträge", "Leistungsaustausch", "Entgelt"],
},
{
  id: "npo-029",
  category: "NPO und Gemeinnützigkeit",
  topic: "Mittelverwendung",
  type: "true-false",
  difficulty: "schwer",
  question: "Verluste eines steuerpflichtigen wirtschaftlichen Geschäftsbetriebs dürfen grundsätzlich mit Spenden und Mitgliedsbeiträgen ausgeglichen werden.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 1,
  explanation: "Ein dauerhafter Ausgleich von Verlusten des steuerpflichtigen wirtschaftlichen Geschäftsbetriebs mit Mitteln des steuerbegünstigten Bereichs gefährdet die Selbstlosigkeit. Ausnahmen bestehen nur unter engen Voraussetzungen.",
  reference: "§ 55 AO",
  tags: ["Verlustausgleich", "wirtschaftlicher Geschäftsbetrieb", "Selbstlosigkeit"],
},
{
  id: "npo-030",
  category: "NPO und Gemeinnützigkeit",
  topic: "Hilfspersonen",
  type: "single-choice",
  difficulty: "schwer",
  question: "Was ist beim Einsatz einer Hilfsperson zur Zweckverwirklichung besonders wichtig?",
  options: [
    "Die Hilfsperson muss Mitglied sein",
    "Die Tätigkeit muss vertraglich gesteuert, überwacht und dokumentiert werden",
    "Die Hilfsperson darf keine Vergütung erhalten",
    "Die Körperschaft darf keinerlei Weisungsrechte haben",
  ],
  correctAnswer: 1,
  explanation: "Beim Einsatz von Hilfspersonen muss die Körperschaft sicherstellen und nachweisen, dass deren Tätigkeit wie eigenes Handeln der Körperschaft zuzurechnen ist.",
  reference: "§ 57 Abs. 1 AO",
  tags: ["Hilfsperson", "Unmittelbarkeit", "Dokumentation"],
},
{
  id: "npo-031",
  category: "NPO und Gemeinnützigkeit",
  topic: "Kooperationen",
  type: "true-false",
  difficulty: "schwer",
  question: "Ein arbeitsteiliges Zusammenwirken mehrerer steuerbegünstigter Körperschaften kann nach § 57 Abs. 3 AO unmittelbar steuerbegünstigt sein.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 0,
  explanation: "§ 57 Abs. 3 AO ermöglicht ein arbeitsteiliges Zusammenwirken steuerbegünstigter Körperschaften. Satzung, Kooperation und tatsächliche Durchführung müssen dazu sauber aufeinander abgestimmt sein.",
  reference: "§ 57 Abs. 3 AO",
  tags: ["Kooperation", "Zusammenwirken", "§57 AO"],
},
{
  id: "npo-032",
  category: "NPO und Gemeinnützigkeit",
  topic: "Förderung der Allgemeinheit",
  type: "single-choice",
  difficulty: "schwer",
  question: "Wann kann die Förderung der Allgemeinheit problematisch sein?",
  options: [
    "Wenn der begünstigte Personenkreis dauerhaft eng abgeschlossen ist",
    "Wenn viele Personen gefördert werden",
    "Wenn die Körperschaft bundesweit tätig ist",
    "Wenn Mitgliedsbeiträge erhoben werden",
  ],
  correctAnswer: 0,
  explanation: "Der begünstigte Personenkreis muss grundsätzlich einen Ausschnitt der Allgemeinheit bilden. Ein dauerhaft eng abgeschlossener Kreis kann die Gemeinnützigkeit ausschließen.",
  reference: "§ 52 AO",
  tags: ["Allgemeinheit", "Personenkreis", "§52 AO"],
},
{
  id: "npo-033",
  category: "NPO und Gemeinnützigkeit",
  topic: "Aktuelle Entwicklungen",
  type: "single-choice",
  difficulty: "mittel",
  question: "Welcher Zweck wurde nach dem in der Wissensdatenbank zugrunde gelegten Rechtsstand seit 2026 ausdrücklich als gemeinnützig anerkannt?",
  options: ["E-Sport", "Kommerzieller Onlinehandel", "Private Vermögensverwaltung", "Parteipolitische Werbung"],
  correctAnswer: 0,
  explanation: "Nach dem in der Wissensdatenbank zugrunde gelegten Rechtsstand ist E-Sport seit 2026 im gesetzlichen Rahmen als gemeinnütziger Zweck anerkannt.",
  reference: "§ 52 AO",
  tags: ["E-Sport", "2026", "gemeinnütziger Zweck"],
},
{
  id: "npo-034",
  category: "NPO und Gemeinnützigkeit",
  topic: "Ehrenamt",
  type: "single-choice",
  difficulty: "mittel",
  question: "Wie hoch ist der Übungsleiterfreibetrag nach dem Rechtsstand 2026?",
  options: ["840 €", "960 €", "3.000 €", "3.300 €"],
  correctAnswer: 3,
  explanation: "Nach dem in der Wissensdatenbank zugrunde gelegten Rechtsstand beträgt der Übungsleiterfreibetrag ab 2026 jährlich 3.300 €.",
  reference: "§ 3 Nr. 26 EStG",
  tags: ["Übungsleiterfreibetrag", "3.300 €", "2026"],
},
{
  id: "npo-035",
  category: "NPO und Gemeinnützigkeit",
  topic: "Ehrenamt",
  type: "single-choice",
  difficulty: "mittel",
  question: "Wie hoch ist die Ehrenamtspauschale nach dem Rechtsstand 2026?",
  options: ["840 €", "960 €", "1.200 €", "3.300 €"],
  correctAnswer: 1,
  explanation: "Nach dem in der Wissensdatenbank zugrunde gelegten Rechtsstand beträgt die Ehrenamtspauschale ab 2026 jährlich 960 €.",
  reference: "§ 3 Nr. 26a EStG",
  tags: ["Ehrenamtspauschale", "960 €", "2026"],
},
{
  id: "npo-036",
  category: "NPO und Gemeinnützigkeit",
  topic: "Zweckbetrieb",
  type: "true-false",
  difficulty: "schwer",
  question: "Hohe Gewinne eines Zweckbetriebs schließen die Gemeinnützigkeit automatisch aus.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 1,
  explanation: "Hohe Gewinne eines Zweckbetriebs führen nicht automatisch zum Verlust der Gemeinnützigkeit. Entscheidend ist, ob die Tätigkeit die Voraussetzungen des Zweckbetriebs erfüllt und die Mittel den steuerbegünstigten Zwecken dienen.",
  reference: "§§ 55, 65–68 AO",
  tags: ["Zweckbetrieb", "Gewinne", "Selbstlosigkeit"],
},
{
  id: "npo-037",
  category: "NPO und Gemeinnützigkeit",
  topic: "Politische Betätigung",
  type: "single-choice",
  difficulty: "schwer",
  question: "Welche politische Betätigung kann gemeinnützigkeitsrechtlich zulässig sein?",
  options: [
    "Parteipolitische Wahlwerbung als Hauptzweck",
    "Sachliche und parteipolitisch neutrale Förderung demokratischer Grundprinzipien",
    "Finanzierung einer einzelnen Partei",
    "Beliebige politische Kampagnen ohne Satzungsbezug",
  ],
  correctAnswer: 1,
  explanation: "Politische Einflussnahme als eigenständiger Zweck ist grundsätzlich nicht gemeinnützig. Eine sachliche, neutrale Befassung mit demokratischen Grundprinzipien kann dagegen begünstigt sein.",
  reference: "§ 52 AO",
  tags: ["politische Betätigung", "demokratisches Staatswesen", "Neutralität"],
},
{
  id: "npo-038",
  category: "NPO und Gemeinnützigkeit",
  topic: "Satzung",
  type: "true-false",
  difficulty: "schwer",
  question: "Eine sehr offene Satzungsformulierung mit dem Wort „insbesondere“ ist immer unschädlich.",
  options: ["Richtig", "Falsch"],
  correctAnswer: 1,
  explanation: "Offene Formulierungen können problematisch sein, wenn sie die Verfolgung weiterer, nicht hinreichend bestimmter Zwecke ermöglichen. Zweck und Zweckverwirklichung müssen klar festgelegt sein.",
  reference: "§ 60 AO; Anlage 1 zu § 60 AO",
  tags: ["Satzung", "Bestimmtheit", "Mustersatzung"],
},
{
  id: "npo-039",
  category: "NPO und Gemeinnützigkeit",
  topic: "Vorsteuerpauschale",
  type: "single-choice",
  difficulty: "schwer",
  question: "Welche Vorschrift regelt die Vorsteuerpauschale für bestimmte steuerbegünstigte Körperschaften?",
  options: ["§ 23a UStG", "§ 10b EStG", "§ 62 AO", "§ 5 KStG"],
  correctAnswer: 0,
  explanation: "Die Vorsteuerpauschale für bestimmte steuerbegünstigte Körperschaften ist in § 23a UStG geregelt.",
  reference: "§ 23a UStG",
  tags: ["Vorsteuerpauschale", "Umsatzsteuer", "§23a UStG"],
},
{
  id: "npo-040",
  category: "NPO und Gemeinnützigkeit",
  topic: "Praxisfall",
  type: "single-choice",
  difficulty: "schwer",
  question: "Ein Verein erhält 10.000 € von einem Unternehmen und veröffentlicht dafür dessen Logo mit Werbelink. Welche Einordnung liegt am nächsten?",
  options: [
    "Reine Spende ohne Gegenleistung",
    "Sponsoring mit Leistungsaustausch",
    "Echter Mitgliedsbeitrag",
    "Vermögenszuführung ohne steuerliche Folgen",
  ],
  correctAnswer: 1,
  explanation: "Die aktive Logo-Veröffentlichung mit Werbelink ist eine konkrete Gegenleistung. Daher liegt regelmäßig Sponsoring mit umsatzsteuerlich relevantem Leistungsaustausch nahe.",
  reference: "§ 1 Abs. 1 Nr. 1 UStG; § 10b EStG",
  hint: "Entscheidend ist, ob der Geldgeber eine konkrete Werbeleistung erhält.",
  tags: ["Praxisfall", "Sponsoring", "Logo", "Leistungsaustausch"],
},
'''

text = text.replace(needle, extra + needle, 1)
path.write_text(text, encoding='utf-8')

Path('scripts/expand-npo-learning-questions.py').unlink(missing_ok=True)
