/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// Manual replacement used because the browser editor does not run the route generator.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WissensdatenbankRouteImport } from './routes/wissensdatenbank'
import { Route as SkrKonverterRouteImport } from './routes/skr-konverter'
import { Route as NpoPruefassistentRouteImport } from './routes/npo-pruefassistent'
import { Route as NeueAnfrageRouteImport } from './routes/neue-anfrage'
import { Route as MittelverwendungsrechnerRouteImport } from './routes/mittelverwendungsrechner'
import { Route as LerngebieteRouteImport } from './routes/lerngebiete'
import { Route as LernenRouteImport } from './routes/lernen'
import { Route as KfzWertabgabeRouteImport } from './routes/kfz-wertabgabe'
import { Route as GesetzImportierenRouteImport } from './routes/gesetz-importieren'
import { Route as FallverlaufRouteImport } from './routes/fallverlauf'
import { Route as ErfolgeRouteImport } from './routes/erfolge'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as CsvKonverterRouteImport } from './routes/csv-konverter'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AkademieRouteImport } from './routes/akademie'
import { Route as MagazinRouteImport } from './routes/magazin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FallCaseIdRouteImport } from './routes/fall.$caseId'
import { Route as ApiAnalyzeDocumentRouteImport } from './routes/api/analyze-document'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WissensdatenbankRoute = WissensdatenbankRouteImport.update({
  id: '/wissensdatenbank',
  path: '/wissensdatenbank',
  getParentRoute: () => rootRouteImport,
} as any)
const SkrKonverterRoute = SkrKonverterRouteImport.update({
  id: '/skr-konverter',
  path: '/skr-konverter',
  getParentRoute: () => rootRouteImport,
} as any)
const NpoPruefassistentRoute = NpoPruefassistentRouteImport.update({
  id: '/npo-pruefassistent',
  path: '/npo-pruefassistent',
  getParentRoute: () => rootRouteImport,
} as any)
const NeueAnfrageRoute = NeueAnfrageRouteImport.update({
  id: '/neue-anfrage',
  path: '/neue-anfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const MittelverwendungsrechnerRoute = MittelverwendungsrechnerRouteImport.update({
  id: '/mittelverwendungsrechner',
  path: '/mittelverwendungsrechner',
  getParentRoute: () => rootRouteImport,
} as any)
const LerngebieteRoute = LerngebieteRouteImport.update({
  id: '/lerngebiete',
  path: '/lerngebiete',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenRoute = LernenRouteImport.update({
  id: '/lernen',
  path: '/lernen',
  getParentRoute: () => rootRouteImport,
} as any)
const KfzWertabgabeRoute = KfzWertabgabeRouteImport.update({
  id: '/kfz-wertabgabe',
  path: '/kfz-wertabgabe',
  getParentRoute: () => rootRouteImport,
} as any)
const GesetzImportierenRoute = GesetzImportierenRouteImport.update({
  id: '/gesetz-importieren',
  path: '/gesetz-importieren',
  getParentRoute: () => rootRouteImport,
} as any)
const FallverlaufRoute = FallverlaufRouteImport.update({
  id: '/fallverlauf',
  path: '/fallverlauf',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfolgeRoute = ErfolgeRouteImport.update({
  id: '/erfolge',
  path: '/erfolge',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvKonverterRoute = CsvKonverterRouteImport.update({
  id: '/csv-konverter',
  path: '/csv-konverter',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AkademieRoute = AkademieRouteImport.update({
  id: '/akademie',
  path: '/akademie',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinRoute = MagazinRouteImport.update({
  id: '/magazin',
  path: '/magazin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FallCaseIdRoute = FallCaseIdRouteImport.update({
  id: '/fall/$caseId',
  path: '/fall/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeDocumentRoute = ApiAnalyzeDocumentRouteImport.update({
  id: '/api/analyze-document',
  path: '/api/analyze-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/wissensdatenbank': typeof WissensdatenbankRoute
  '/skr-konverter': typeof SkrKonverterRoute
  '/npo-pruefassistent': typeof NpoPruefassistentRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/mittelverwendungsrechner': typeof MittelverwendungsrechnerRoute
  '/lerngebiete': typeof LerngebieteRoute
  '/lernen': typeof LernenRoute
  '/kfz-wertabgabe': typeof KfzWertabgabeRoute
  '/gesetz-importieren': typeof GesetzImportierenRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/erfolge': typeof ErfolgeRoute
  '/einstellungen': typeof EinstellungenRoute
  '/csv-konverter': typeof CsvKonverterRoute
  '/chat': typeof ChatRoute
  '/akademie': typeof AkademieRoute
  '/magazin': typeof MagazinRoute
  '/': typeof IndexRoute
  '/fall/$caseId': typeof FallCaseIdRoute
  '/api/analyze-document': typeof ApiAnalyzeDocumentRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/wissensdatenbank': typeof WissensdatenbankRoute
  '/skr-konverter': typeof SkrKonverterRoute
  '/npo-pruefassistent': typeof NpoPruefassistentRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/mittelverwendungsrechner': typeof MittelverwendungsrechnerRoute
  '/lerngebiete': typeof LerngebieteRoute
  '/lernen': typeof LernenRoute
  '/kfz-wertabgabe': typeof KfzWertabgabeRoute
  '/gesetz-importieren': typeof GesetzImportierenRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/erfolge': typeof ErfolgeRoute
  '/einstellungen': typeof EinstellungenRoute
  '/csv-konverter': typeof CsvKonverterRoute
  '/chat': typeof ChatRoute
  '/akademie': typeof AkademieRoute
  '/magazin': typeof MagazinRoute
  '/': typeof IndexRoute
  '/fall/$caseId': typeof FallCaseIdRoute
  '/api/analyze-document': typeof ApiAnalyzeDocumentRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/wissensdatenbank': typeof WissensdatenbankRoute
  '/skr-konverter': typeof SkrKonverterRoute
  '/npo-pruefassistent': typeof NpoPruefassistentRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/mittelverwendungsrechner': typeof MittelverwendungsrechnerRoute
  '/lerngebiete': typeof LerngebieteRoute
  '/lernen': typeof LernenRoute
  '/kfz-wertabgabe': typeof KfzWertabgabeRoute
  '/gesetz-importieren': typeof GesetzImportierenRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/erfolge': typeof ErfolgeRoute
  '/einstellungen': typeof EinstellungenRoute
  '/csv-konverter': typeof CsvKonverterRoute
  '/chat': typeof ChatRoute
  '/akademie': typeof AkademieRoute
  '/magazin': typeof MagazinRoute
  '/': typeof IndexRoute
  '/fall/$caseId': typeof FallCaseIdRoute
  '/api/analyze-document': typeof ApiAnalyzeDocumentRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/wissensdatenbank'
    | '/skr-konverter'
    | '/npo-pruefassistent'
    | '/neue-anfrage'
    | '/mittelverwendungsrechner'
    | '/lerngebiete'
    | '/lernen'
    | '/kfz-wertabgabe'
    | '/gesetz-importieren'
    | '/fallverlauf'
    | '/erfolge'
    | '/einstellungen'
    | '/csv-konverter'
    | '/chat'
    | '/akademie'
    | '/magazin'
    | '/'
    | '/fall/$caseId'
    | '/api/analyze-document'
    | '/api/transcribe'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/wissensdatenbank'
    | '/skr-konverter'
    | '/npo-pruefassistent'
    | '/neue-anfrage'
    | '/mittelverwendungsrechner'
    | '/lerngebiete'
    | '/lernen'
    | '/kfz-wertabgabe'
    | '/gesetz-importieren'
    | '/fallverlauf'
    | '/erfolge'
    | '/einstellungen'
    | '/csv-konverter'
    | '/chat'
    | '/akademie'
    | '/magazin'
    | '/'
    | '/fall/$caseId'
    | '/api/analyze-document'
    | '/api/transcribe'
    | '/api/chat'
  id:
    | '__root__'
    | '/wissensdatenbank'
    | '/skr-konverter'
    | '/npo-pruefassistent'
    | '/neue-anfrage'
    | '/mittelverwendungsrechner'
    | '/lerngebiete'
    | '/lernen'
    | '/kfz-wertabgabe'
    | '/gesetz-importieren'
    | '/fallverlauf'
    | '/erfolge'
    | '/einstellungen'
    | '/csv-konverter'
    | '/chat'
    | '/akademie'
    | '/magazin'
    | '/'
    | '/fall/$caseId'
    | '/api/analyze-document'
    | '/api/transcribe'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WissensdatenbankRoute: typeof WissensdatenbankRoute
  SkrKonverterRoute: typeof SkrKonverterRoute
  NpoPruefassistentRoute: typeof NpoPruefassistentRoute
  NeueAnfrageRoute: typeof NeueAnfrageRoute
  MittelverwendungsrechnerRoute: typeof MittelverwendungsrechnerRoute
  LerngebieteRoute: typeof LerngebieteRoute
  LernenRoute: typeof LernenRoute
  KfzWertabgabeRoute: typeof KfzWertabgabeRoute
  GesetzImportierenRoute: typeof GesetzImportierenRoute
  FallverlaufRoute: typeof FallverlaufRoute
  ErfolgeRoute: typeof ErfolgeRoute
  EinstellungenRoute: typeof EinstellungenRoute
  CsvKonverterRoute: typeof CsvKonverterRoute
  ChatRoute: typeof ChatRoute
  AkademieRoute: typeof AkademieRoute
  MagazinRoute: typeof MagazinRoute
  IndexRoute: typeof IndexRoute
  FallCaseIdRoute: typeof FallCaseIdRoute
  ApiAnalyzeDocumentRoute: typeof ApiAnalyzeDocumentRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wissensdatenbank': {
      id: '/wissensdatenbank'
      path: '/wissensdatenbank'
      fullPath: '/wissensdatenbank'
      preLoaderRoute: typeof WissensdatenbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skr-konverter': {
      id: '/skr-konverter'
      path: '/skr-konverter'
      fullPath: '/skr-konverter'
      preLoaderRoute: typeof SkrKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npo-pruefassistent': {
      id: '/npo-pruefassistent'
      path: '/npo-pruefassistent'
      fullPath: '/npo-pruefassistent'
      preLoaderRoute: typeof NpoPruefassistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neue-anfrage': {
      id: '/neue-anfrage'
      path: '/neue-anfrage'
      fullPath: '/neue-anfrage'
      preLoaderRoute: typeof NeueAnfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mittelverwendungsrechner': {
      id: '/mittelverwendungsrechner'
      path: '/mittelverwendungsrechner'
      fullPath: '/mittelverwendungsrechner'
      preLoaderRoute: typeof MittelverwendungsrechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lerngebiete': {
      id: '/lerngebiete'
      path: '/lerngebiete'
      fullPath: '/lerngebiete'
      preLoaderRoute: typeof LerngebieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen': {
      id: '/lernen'
      path: '/lernen'
      fullPath: '/lernen'
      preLoaderRoute: typeof LernenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kfz-wertabgabe': {
      id: '/kfz-wertabgabe'
      path: '/kfz-wertabgabe'
      fullPath: '/kfz-wertabgabe'
      preLoaderRoute: typeof KfzWertabgabeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gesetz-importieren': {
      id: '/gesetz-importieren'
      path: '/gesetz-importieren'
      fullPath: '/gesetz-importieren'
      preLoaderRoute: typeof GesetzImportierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallverlauf': {
      id: '/fallverlauf'
      path: '/fallverlauf'
      fullPath: '/fallverlauf'
      preLoaderRoute: typeof FallverlaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfolge': {
      id: '/erfolge'
      path: '/erfolge'
      fullPath: '/erfolge'
      preLoaderRoute: typeof ErfolgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-konverter': {
      id: '/csv-konverter'
      path: '/csv-konverter'
      fullPath: '/csv-konverter'
      preLoaderRoute: typeof CsvKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akademie': {
      id: '/akademie'
      path: '/akademie'
      fullPath: '/akademie'
      preLoaderRoute: typeof AkademieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazin': {
      id: '/magazin'
      path: '/magazin'
      fullPath: '/magazin'
      preLoaderRoute: typeof MagazinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall/$caseId': {
      id: '/fall/$caseId'
      path: '/fall/$caseId'
      fullPath: '/fall/$caseId'
      preLoaderRoute: typeof FallCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-document': {
      id: '/api/analyze-document'
      path: '/api/analyze-document'
      fullPath: '/api/analyze-document'
      preLoaderRoute: typeof ApiAnalyzeDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WissensdatenbankRoute: WissensdatenbankRoute,
  SkrKonverterRoute: SkrKonverterRoute,
  NpoPruefassistentRoute: NpoPruefassistentRoute,
  NeueAnfrageRoute: NeueAnfrageRoute,
  MittelverwendungsrechnerRoute: MittelverwendungsrechnerRoute,
  LerngebieteRoute: LerngebieteRoute,
  LernenRoute: LernenRoute,
  KfzWertabgabeRoute: KfzWertabgabeRoute,
  GesetzImportierenRoute: GesetzImportierenRoute,
  FallverlaufRoute: FallverlaufRoute,
  ErfolgeRoute: ErfolgeRoute,
  EinstellungenRoute: EinstellungenRoute,
  CsvKonverterRoute: CsvKonverterRoute,
  ChatRoute: ChatRoute,
  AkademieRoute: AkademieRoute,
  MagazinRoute: MagazinRoute,
  IndexRoute: IndexRoute,
  FallCaseIdRoute: FallCaseIdRoute,
  ApiAnalyzeDocumentRoute: ApiAnalyzeDocumentRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
