/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WissensdatenbankRouteImport } from './routes/wissensdatenbank'
import { Route as SkrKonverterRouteImport } from './routes/skr-konverter'
import { Route as NpoPruefassistentRouteImport } from './routes/npo-pruefassistent'
import { Route as NeueAnfrageRouteImport } from './routes/neue-anfrage'
import { Route as MittelverwendungsrechnerRouteImport } from './routes/mittelverwendungsrechner'
import { Route as MagazinRouteImport } from './routes/magazin'
import { Route as LerngebieteRouteImport } from './routes/lerngebiete'
import { Route as LernenRouteImport } from './routes/lernen'
import { Route as KfzWertabgabeRouteImport } from './routes/kfz-wertabgabe'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GesetzImportierenRouteImport } from './routes/gesetz-importieren'
import { Route as FristenkalenderRouteImport } from './routes/fristenkalender'
import { Route as FallverlaufRouteImport } from './routes/fallverlauf'
import { Route as ErfolgeRouteImport } from './routes/erfolge'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as CsvKonverterRouteImport } from './routes/csv-konverter'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LernenPruefungssimulationRouteImport } from './routes/lernen_.pruefungssimulation'
import { Route as LernenAkademieRouteImport } from './routes/lernen_.akademie'
import { Route as FallCaseIdRouteImport } from './routes/fall.$caseId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTextToSpeechRouteImport } from './routes/api/text-to-speech'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LernenAkademieKlausurenRouteImport } from './routes/lernen_.akademie_.klausuren'
import { Route as LernenAkademieFortschrittRouteImport } from './routes/lernen_.akademie_.fortschritt'
import { Route as LernenAkademieFehlertrainerRouteImport } from './routes/lernen_.akademie_.fehlertrainer'
import { Route as LernenAkademieFavoritenRouteImport } from './routes/lernen_.akademie_.favoriten'
import { Route as ApiUploadUploadIdRouteImport } from './routes/api/upload.$uploadId'
import { Route as LernenAkademieKlausurenSlugRouteImport } from './routes/lernen_.akademie_.klausuren_.$slug'
import { Route as LernenAkademieFehlertrainerTrainingRouteImport } from './routes/lernen_.akademie_.fehlertrainer_.training'

const WissensdatenbankRoute = WissensdatenbankRouteImport.update({
  id: '/wissensdatenbank',
  path: '/wissensdatenbank',
  getParentRoute: () => rootRouteImport,
} as any)
const SkrKonverterRoute = SkrKonverterRouteImport.update({
  id: '/skr-konverter',
  path: '/skr-konverter',
  getParentRoute: () => rootRouteImport,
} as any)
const NpoPruefassistentRoute = NpoPruefassistentRouteImport.update({
  id: '/npo-pruefassistent',
  path: '/npo-pruefassistent',
  getParentRoute: () => rootRouteImport,
} as any)
const NeueAnfrageRoute = NeueAnfrageRouteImport.update({
  id: '/neue-anfrage',
  path: '/neue-anfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const MittelverwendungsrechnerRoute =
  MittelverwendungsrechnerRouteImport.update({
    id: '/mittelverwendungsrechner',
    path: '/mittelverwendungsrechner',
    getParentRoute: () => rootRouteImport,
  } as any)
const MagazinRoute = MagazinRouteImport.update({
  id: '/magazin',
  path: '/magazin',
  getParentRoute: () => rootRouteImport,
} as any)
const LerngebieteRoute = LerngebieteRouteImport.update({
  id: '/lerngebiete',
  path: '/lerngebiete',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenRoute = LernenRouteImport.update({
  id: '/lernen',
  path: '/lernen',
  getParentRoute: () => rootRouteImport,
} as any)
const KfzWertabgabeRoute = KfzWertabgabeRouteImport.update({
  id: '/kfz-wertabgabe',
  path: '/kfz-wertabgabe',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GesetzImportierenRoute = GesetzImportierenRouteImport.update({
  id: '/gesetz-importieren',
  path: '/gesetz-importieren',
  getParentRoute: () => rootRouteImport,
} as any)
const FristenkalenderRoute = FristenkalenderRouteImport.update({
  id: '/fristenkalender',
  path: '/fristenkalender',
  getParentRoute: () => rootRouteImport,
} as any)
const FallverlaufRoute = FallverlaufRouteImport.update({
  id: '/fallverlauf',
  path: '/fallverlauf',
  getParentRoute: () => rootRouteImport,
} as any)
const ErfolgeRoute = ErfolgeRouteImport.update({
  id: '/erfolge',
  path: '/erfolge',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvKonverterRoute = CsvKonverterRouteImport.update({
  id: '/csv-konverter',
  path: '/csv-konverter',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenPruefungssimulationRoute =
  LernenPruefungssimulationRouteImport.update({
    id: '/lernen_/pruefungssimulation',
    path: '/lernen/pruefungssimulation',
    getParentRoute: () => rootRouteImport,
  } as any)
const LernenAkademieRoute = LernenAkademieRouteImport.update({
  id: '/lernen_/akademie',
  path: '/lernen/akademie',
  getParentRoute: () => rootRouteImport,
} as any)
const FallCaseIdRoute = FallCaseIdRouteImport.update({
  id: '/fall/$caseId',
  path: '/fall/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTextToSpeechRoute = ApiTextToSpeechRouteImport.update({
  id: '/api/text-to-speech',
  path: '/api/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenAkademieKlausurenRoute = LernenAkademieKlausurenRouteImport.update({
  id: '/lernen_/akademie_/klausuren',
  path: '/lernen/akademie/klausuren',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenAkademieFortschrittRoute =
  LernenAkademieFortschrittRouteImport.update({
    id: '/lernen_/akademie_/fortschritt',
    path: '/lernen/akademie/fortschritt',
    getParentRoute: () => rootRouteImport,
  } as any)
const LernenAkademieFehlertrainerRoute =
  LernenAkademieFehlertrainerRouteImport.update({
    id: '/lernen_/akademie_/fehlertrainer',
    path: '/lernen/akademie/fehlertrainer',
    getParentRoute: () => rootRouteImport,
  } as any)
const LernenAkademieFavoritenRoute = LernenAkademieFavoritenRouteImport.update({
  id: '/lernen_/akademie_/favoriten',
  path: '/lernen/akademie/favoriten',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadUploadIdRoute = ApiUploadUploadIdRouteImport.update({
  id: '/$uploadId',
  path: '/$uploadId',
  getParentRoute: () => ApiUploadRoute,
} as any)
const LernenAkademieKlausurenSlugRoute =
  LernenAkademieKlausurenSlugRouteImport.update({
    id: '/lernen_/akademie_/klausuren_/$slug',
    path: '/lernen/akademie/klausuren/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const LernenAkademieFehlertrainerTrainingRoute =
  LernenAkademieFehlertrainerTrainingRouteImport.update({
    id: '/lernen_/akademie_/fehlertrainer_/training',
    path: '/lernen/akademie/fehlertrainer/training',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/csv-konverter': typeof CsvKonverterRoute
  '/einstellungen': typeof EinstellungenRoute
  '/erfolge': typeof ErfolgeRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/fristenkalender': typeof FristenkalenderRoute
  '/gesetz-importieren': typeof GesetzImportierenRoute
  '/impressum': typeof ImpressumRoute
  '/kfz-wertabgabe': typeof KfzWertabgabeRoute
  '/lernen': typeof LernenRoute
  '/lerngebiete': typeof LerngebieteRoute
  '/magazin': typeof MagazinRoute
  '/mittelverwendungsrechner': typeof MittelverwendungsrechnerRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/npo-pruefassistent': typeof NpoPruefassistentRoute
  '/skr-konverter': typeof SkrKonverterRoute
  '/wissensdatenbank': typeof WissensdatenbankRoute
  '/api/chat': typeof ApiChatRoute
  '/api/text-to-speech': typeof ApiTextToSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/upload': typeof ApiUploadRouteWithChildren
  '/fall/$caseId': typeof FallCaseIdRoute
  '/lernen/akademie': typeof LernenAkademieRoute
  '/lernen/pruefungssimulation': typeof LernenPruefungssimulationRoute
  '/api/upload/$uploadId': typeof ApiUploadUploadIdRoute
  '/lernen/akademie/favoriten': typeof LernenAkademieFavoritenRoute
  '/lernen/akademie/fehlertrainer': typeof LernenAkademieFehlertrainerRoute
  '/lernen/akademie/fortschritt': typeof LernenAkademieFortschrittRoute
  '/lernen/akademie/klausuren': typeof LernenAkademieKlausurenRoute
  '/lernen/akademie/fehlertrainer/training': typeof LernenAkademieFehlertrainerTrainingRoute
  '/lernen/akademie/klausuren/$slug': typeof LernenAkademieKlausurenSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/csv-konverter': typeof CsvKonverterRoute
  '/einstellungen': typeof EinstellungenRoute
  '/erfolge': typeof ErfolgeRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/fristenkalender': typeof FristenkalenderRoute
  '/gesetz-importieren': typeof GesetzImportierenRoute
  '/impressum': typeof ImpressumRoute
  '/kfz-wertabgabe': typeof KfzWertabgabeRoute
  '/lernen': typeof LernenRoute
  '/lerngebiete': typeof LerngebieteRoute
  '/magazin': typeof MagazinRoute
  '/mittelverwendungsrechner': typeof MittelverwendungsrechnerRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/npo-pruefassistent': typeof NpoPruefassistentRoute
  '/skr-konverter': typeof SkrKonverterRoute
  '/wissensdatenbank': typeof WissensdatenbankRoute
  '/api/chat': typeof ApiChatRoute
  '/api/text-to-speech': typeof ApiTextToSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/upload': typeof ApiUploadRouteWithChildren
  '/fall/$caseId': typeof FallCaseIdRoute
  '/lernen/akademie': typeof LernenAkademieRoute
  '/lernen/pruefungssimulation': typeof LernenPruefungssimulationRoute
  '/api/upload/$uploadId': typeof ApiUploadUploadIdRoute
  '/lernen/akademie/favoriten': typeof LernenAkademieFavoritenRoute
  '/lernen/akademie/fehlertrainer': typeof LernenAkademieFehlertrainerRoute
  '/lernen/akademie/fortschritt': typeof LernenAkademieFortschrittRoute
  '/lernen/akademie/klausuren': typeof LernenAkademieKlausurenRoute
  '/lernen/akademie/fehlertrainer/training': typeof LernenAkademieFehlertrainerTrainingRoute
  '/lernen/akademie/klausuren/$slug': typeof LernenAkademieKlausurenSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/csv-konverter': typeof CsvKonverterRoute
  '/einstellungen': typeof EinstellungenRoute
  '/erfolge': typeof ErfolgeRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/fristenkalender': typeof FristenkalenderRoute
  '/gesetz-importieren': typeof GesetzImportierenRoute
  '/impressum': typeof ImpressumRoute
  '/kfz-wertabgabe': typeof KfzWertabgabeRoute
  '/lernen': typeof LernenRoute
  '/lerngebiete': typeof LerngebieteRoute
  '/magazin': typeof MagazinRoute
  '/mittelverwendungsrechner': typeof MittelverwendungsrechnerRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/npo-pruefassistent': typeof NpoPruefassistentRoute
  '/skr-konverter': typeof SkrKonverterRoute
  '/wissensdatenbank': typeof WissensdatenbankRoute
  '/api/chat': typeof ApiChatRoute
  '/api/text-to-speech': typeof ApiTextToSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/upload': typeof ApiUploadRouteWithChildren
  '/fall/$caseId': typeof FallCaseIdRoute
  '/lernen_/akademie': typeof LernenAkademieRoute
  '/lernen_/pruefungssimulation': typeof LernenPruefungssimulationRoute
  '/api/upload/$uploadId': typeof ApiUploadUploadIdRoute
  '/lernen_/akademie_/favoriten': typeof LernenAkademieFavoritenRoute
  '/lernen_/akademie_/fehlertrainer': typeof LernenAkademieFehlertrainerRoute
  '/lernen_/akademie_/fortschritt': typeof LernenAkademieFortschrittRoute
  '/lernen_/akademie_/klausuren': typeof LernenAkademieKlausurenRoute
  '/lernen_/akademie_/fehlertrainer_/training': typeof LernenAkademieFehlertrainerTrainingRoute
  '/lernen_/akademie_/klausuren_/$slug': typeof LernenAkademieKlausurenSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/csv-konverter'
    | '/einstellungen'
    | '/erfolge'
    | '/fallverlauf'
    | '/fristenkalender'
    | '/gesetz-importieren'
    | '/impressum'
    | '/kfz-wertabgabe'
    | '/lernen'
    | '/lerngebiete'
    | '/magazin'
    | '/mittelverwendungsrechner'
    | '/neue-anfrage'
    | '/npo-pruefassistent'
    | '/skr-konverter'
    | '/wissensdatenbank'
    | '/api/chat'
    | '/api/text-to-speech'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/upload'
    | '/fall/$caseId'
    | '/lernen/akademie'
    | '/lernen/pruefungssimulation'
    | '/api/upload/$uploadId'
    | '/lernen/akademie/favoriten'
    | '/lernen/akademie/fehlertrainer'
    | '/lernen/akademie/fortschritt'
    | '/lernen/akademie/klausuren'
    | '/lernen/akademie/fehlertrainer/training'
    | '/lernen/akademie/klausuren/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/csv-konverter'
    | '/einstellungen'
    | '/erfolge'
    | '/fallverlauf'
    | '/fristenkalender'
    | '/gesetz-importieren'
    | '/impressum'
    | '/kfz-wertabgabe'
    | '/lernen'
    | '/lerngebiete'
    | '/magazin'
    | '/mittelverwendungsrechner'
    | '/neue-anfrage'
    | '/npo-pruefassistent'
    | '/skr-konverter'
    | '/wissensdatenbank'
    | '/api/chat'
    | '/api/text-to-speech'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/upload'
    | '/fall/$caseId'
    | '/lernen/akademie'
    | '/lernen/pruefungssimulation'
    | '/api/upload/$uploadId'
    | '/lernen/akademie/favoriten'
    | '/lernen/akademie/fehlertrainer'
    | '/lernen/akademie/fortschritt'
    | '/lernen/akademie/klausuren'
    | '/lernen/akademie/fehlertrainer/training'
    | '/lernen/akademie/klausuren/$slug'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/csv-konverter'
    | '/einstellungen'
    | '/erfolge'
    | '/fallverlauf'
    | '/fristenkalender'
    | '/gesetz-importieren'
    | '/impressum'
    | '/kfz-wertabgabe'
    | '/lernen'
    | '/lerngebiete'
    | '/magazin'
    | '/mittelverwendungsrechner'
    | '/neue-anfrage'
    | '/npo-pruefassistent'
    | '/skr-konverter'
    | '/wissensdatenbank'
    | '/api/chat'
    | '/api/text-to-speech'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/upload'
    | '/fall/$caseId'
    | '/lernen_/akademie'
    | '/lernen_/pruefungssimulation'
    | '/api/upload/$uploadId'
    | '/lernen_/akademie_/favoriten'
    | '/lernen_/akademie_/fehlertrainer'
    | '/lernen_/akademie_/fortschritt'
    | '/lernen_/akademie_/klausuren'
    | '/lernen_/akademie_/fehlertrainer_/training'
    | '/lernen_/akademie_/klausuren_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CsvKonverterRoute: typeof CsvKonverterRoute
  EinstellungenRoute: typeof EinstellungenRoute
  ErfolgeRoute: typeof ErfolgeRoute
  FallverlaufRoute: typeof FallverlaufRoute
  FristenkalenderRoute: typeof FristenkalenderRoute
  GesetzImportierenRoute: typeof GesetzImportierenRoute
  ImpressumRoute: typeof ImpressumRoute
  KfzWertabgabeRoute: typeof KfzWertabgabeRoute
  LernenRoute: typeof LernenRoute
  LerngebieteRoute: typeof LerngebieteRoute
  MagazinRoute: typeof MagazinRoute
  MittelverwendungsrechnerRoute: typeof MittelverwendungsrechnerRoute
  NeueAnfrageRoute: typeof NeueAnfrageRoute
  NpoPruefassistentRoute: typeof NpoPruefassistentRoute
  SkrKonverterRoute: typeof SkrKonverterRoute
  WissensdatenbankRoute: typeof WissensdatenbankRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTextToSpeechRoute: typeof ApiTextToSpeechRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiUploadRoute: typeof ApiUploadRouteWithChildren
  FallCaseIdRoute: typeof FallCaseIdRoute
  LernenAkademieRoute: typeof LernenAkademieRoute
  LernenPruefungssimulationRoute: typeof LernenPruefungssimulationRoute
  LernenAkademieFavoritenRoute: typeof LernenAkademieFavoritenRoute
  LernenAkademieFehlertrainerRoute: typeof LernenAkademieFehlertrainerRoute
  LernenAkademieFortschrittRoute: typeof LernenAkademieFortschrittRoute
  LernenAkademieKlausurenRoute: typeof LernenAkademieKlausurenRoute
  LernenAkademieFehlertrainerTrainingRoute: typeof LernenAkademieFehlertrainerTrainingRoute
  LernenAkademieKlausurenSlugRoute: typeof LernenAkademieKlausurenSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wissensdatenbank': {
      id: '/wissensdatenbank'
      path: '/wissensdatenbank'
      fullPath: '/wissensdatenbank'
      preLoaderRoute: typeof WissensdatenbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skr-konverter': {
      id: '/skr-konverter'
      path: '/skr-konverter'
      fullPath: '/skr-konverter'
      preLoaderRoute: typeof SkrKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npo-pruefassistent': {
      id: '/npo-pruefassistent'
      path: '/npo-pruefassistent'
      fullPath: '/npo-pruefassistent'
      preLoaderRoute: typeof NpoPruefassistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neue-anfrage': {
      id: '/neue-anfrage'
      path: '/neue-anfrage'
      fullPath: '/neue-anfrage'
      preLoaderRoute: typeof NeueAnfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mittelverwendungsrechner': {
      id: '/mittelverwendungsrechner'
      path: '/mittelverwendungsrechner'
      fullPath: '/mittelverwendungsrechner'
      preLoaderRoute: typeof MittelverwendungsrechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazin': {
      id: '/magazin'
      path: '/magazin'
      fullPath: '/magazin'
      preLoaderRoute: typeof MagazinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lerngebiete': {
      id: '/lerngebiete'
      path: '/lerngebiete'
      fullPath: '/lerngebiete'
      preLoaderRoute: typeof LerngebieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen': {
      id: '/lernen'
      path: '/lernen'
      fullPath: '/lernen'
      preLoaderRoute: typeof LernenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kfz-wertabgabe': {
      id: '/kfz-wertabgabe'
      path: '/kfz-wertabgabe'
      fullPath: '/kfz-wertabgabe'
      preLoaderRoute: typeof KfzWertabgabeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gesetz-importieren': {
      id: '/gesetz-importieren'
      path: '/gesetz-importieren'
      fullPath: '/gesetz-importieren'
      preLoaderRoute: typeof GesetzImportierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fristenkalender': {
      id: '/fristenkalender'
      path: '/fristenkalender'
      fullPath: '/fristenkalender'
      preLoaderRoute: typeof FristenkalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallverlauf': {
      id: '/fallverlauf'
      path: '/fallverlauf'
      fullPath: '/fallverlauf'
      preLoaderRoute: typeof FallverlaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erfolge': {
      id: '/erfolge'
      path: '/erfolge'
      fullPath: '/erfolge'
      preLoaderRoute: typeof ErfolgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-konverter': {
      id: '/csv-konverter'
      path: '/csv-konverter'
      fullPath: '/csv-konverter'
      preLoaderRoute: typeof CsvKonverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/pruefungssimulation': {
      id: '/lernen_/pruefungssimulation'
      path: '/lernen/pruefungssimulation'
      fullPath: '/lernen/pruefungssimulation'
      preLoaderRoute: typeof LernenPruefungssimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/akademie': {
      id: '/lernen_/akademie'
      path: '/lernen/akademie'
      fullPath: '/lernen/akademie'
      preLoaderRoute: typeof LernenAkademieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall/$caseId': {
      id: '/fall/$caseId'
      path: '/fall/$caseId'
      fullPath: '/fall/$caseId'
      preLoaderRoute: typeof FallCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/text-to-speech': {
      id: '/api/text-to-speech'
      path: '/api/text-to-speech'
      fullPath: '/api/text-to-speech'
      preLoaderRoute: typeof ApiTextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/akademie_/klausuren': {
      id: '/lernen_/akademie_/klausuren'
      path: '/lernen/akademie/klausuren'
      fullPath: '/lernen/akademie/klausuren'
      preLoaderRoute: typeof LernenAkademieKlausurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/akademie_/fortschritt': {
      id: '/lernen_/akademie_/fortschritt'
      path: '/lernen/akademie/fortschritt'
      fullPath: '/lernen/akademie/fortschritt'
      preLoaderRoute: typeof LernenAkademieFortschrittRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/akademie_/fehlertrainer': {
      id: '/lernen_/akademie_/fehlertrainer'
      path: '/lernen/akademie/fehlertrainer'
      fullPath: '/lernen/akademie/fehlertrainer'
      preLoaderRoute: typeof LernenAkademieFehlertrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/akademie_/favoriten': {
      id: '/lernen_/akademie_/favoriten'
      path: '/lernen/akademie/favoriten'
      fullPath: '/lernen/akademie/favoriten'
      preLoaderRoute: typeof LernenAkademieFavoritenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/$uploadId': {
      id: '/api/upload/$uploadId'
      path: '/$uploadId'
      fullPath: '/api/upload/$uploadId'
      preLoaderRoute: typeof ApiUploadUploadIdRouteImport
      parentRoute: typeof ApiUploadRoute
    }
    '/lernen_/akademie_/klausuren_/$slug': {
      id: '/lernen_/akademie_/klausuren_/$slug'
      path: '/lernen/akademie/klausuren/$slug'
      fullPath: '/lernen/akademie/klausuren/$slug'
      preLoaderRoute: typeof LernenAkademieKlausurenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen_/akademie_/fehlertrainer_/training': {
      id: '/lernen_/akademie_/fehlertrainer_/training'
      path: '/lernen/akademie/fehlertrainer/training'
      fullPath: '/lernen/akademie/fehlertrainer/training'
      preLoaderRoute: typeof LernenAkademieFehlertrainerTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUploadRouteChildren {
  ApiUploadUploadIdRoute: typeof ApiUploadUploadIdRoute
}

const ApiUploadRouteChildren: ApiUploadRouteChildren = {
  ApiUploadUploadIdRoute: ApiUploadUploadIdRoute,
}

const ApiUploadRouteWithChildren = ApiUploadRoute._addFileChildren(
  ApiUploadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CsvKonverterRoute: CsvKonverterRoute,
  EinstellungenRoute: EinstellungenRoute,
  ErfolgeRoute: ErfolgeRoute,
  FallverlaufRoute: FallverlaufRoute,
  FristenkalenderRoute: FristenkalenderRoute,
  GesetzImportierenRoute: GesetzImportierenRoute,
  ImpressumRoute: ImpressumRoute,
  KfzWertabgabeRoute: KfzWertabgabeRoute,
  LernenRoute: LernenRoute,
  LerngebieteRoute: LerngebieteRoute,
  MagazinRoute: MagazinRoute,
  MittelverwendungsrechnerRoute: MittelverwendungsrechnerRoute,
  NeueAnfrageRoute: NeueAnfrageRoute,
  NpoPruefassistentRoute: NpoPruefassistentRoute,
  SkrKonverterRoute: SkrKonverterRoute,
  WissensdatenbankRoute: WissensdatenbankRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTextToSpeechRoute: ApiTextToSpeechRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiUploadRoute: ApiUploadRouteWithChildren,
  FallCaseIdRoute: FallCaseIdRoute,
  LernenAkademieRoute: LernenAkademieRoute,
  LernenPruefungssimulationRoute: LernenPruefungssimulationRoute,
  LernenAkademieFavoritenRoute: LernenAkademieFavoritenRoute,
  LernenAkademieFehlertrainerRoute: LernenAkademieFehlertrainerRoute,
  LernenAkademieFortschrittRoute: LernenAkademieFortschrittRoute,
  LernenAkademieKlausurenRoute: LernenAkademieKlausurenRoute,
  LernenAkademieFehlertrainerTrainingRoute:
    LernenAkademieFehlertrainerTrainingRoute,
  LernenAkademieKlausurenSlugRoute: LernenAkademieKlausurenSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
