/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WissensdatenbankRouteImport } from './routes/wissensdatenbank'
import { Route as NeueAnfrageRouteImport } from './routes/neue-anfrage'
import { Route as FallverlaufRouteImport } from './routes/fallverlauf'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as IndexRouteImport } from './routes/index'

const WissensdatenbankRoute = WissensdatenbankRouteImport.update({
  id: '/wissensdatenbank',
  path: '/wissensdatenbank',
  getParentRoute: () => rootRouteImport,
} as any)
const NeueAnfrageRoute = NeueAnfrageRouteImport.update({
  id: '/neue-anfrage',
  path: '/neue-anfrage',
  getParentRoute: () => rootRouteImport,
} as any)
const FallverlaufRoute = FallverlaufRouteImport.update({
  id: '/fallverlauf',
  path: '/fallverlauf',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/wissensdatenbank': typeof WissensdatenbankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/wissensdatenbank': typeof WissensdatenbankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/fallverlauf': typeof FallverlaufRoute
  '/neue-anfrage': typeof NeueAnfrageRoute
  '/wissensdatenbank': typeof WissensdatenbankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einstellungen'
    | '/fallverlauf'
    | '/neue-anfrage'
    | '/wissensdatenbank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einstellungen'
    | '/fallverlauf'
    | '/neue-anfrage'
    | '/wissensdatenbank'
  id:
    | '__root__'
    | '/'
    | '/einstellungen'
    | '/fallverlauf'
    | '/neue-anfrage'
    | '/wissensdatenbank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinstellungenRoute: typeof EinstellungenRoute
  FallverlaufRoute: typeof FallverlaufRoute
  NeueAnfrageRoute: typeof NeueAnfrageRoute
  WissensdatenbankRoute: typeof WissensdatenbankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wissensdatenbank': {
      id: '/wissensdatenbank'
      path: '/wissensdatenbank'
      fullPath: '/wissensdatenbank'
      preLoaderRoute: typeof WissensdatenbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neue-anfrage': {
      id: '/neue-anfrage'
      path: '/neue-anfrage'
      fullPath: '/neue-anfrage'
      preLoaderRoute: typeof NeueAnfrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fallverlauf': {
      id: '/fallverlauf'
      path: '/fallverlauf'
      fullPath: '/fallverlauf'
      preLoaderRoute: typeof FallverlaufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinstellungenRoute: EinstellungenRoute,
  FallverlaufRoute: FallverlaufRoute,
  NeueAnfrageRoute: NeueAnfrageRoute,
  WissensdatenbankRoute: WissensdatenbankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
